#!/bin/bash

#SBATCH -J rawGemv
#SBATCH -o filename_%j.txt
#SBATCH -e filename_%j.err
#SBATCH --mail-type=ALL
#SBATCH --mail-user=manya227@stanford.edu
#SBATCH --nodes=1
#SBATCH --mem MaxMemPerNode
#SBATCH --exclusive
#SBATCH --time=10:00:00

systems=("tensor-gsl" "taco" "tblis")

for i in "${systems[@]}"
do  
    cd /home/manya227/taco-interoperable/bench/gemv_raw
    make $i
done



